In [164]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import seaborn as sns
sns.set()
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [215]:
df = pd.read_csv('Absenteeism-preprocessed.csv')

In [217]:
targets = np.where(df['Absenteeism Time in Hours']>df['Absenteeism Time in Hours'].median(),1,0)
df

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  Absenteeism Time in Hours  
0                 30          0         2    1                          4  
1                 31          0         1    0                          0  
2                 31          0         0    0                          2  
3                 24          0         2    0                          4  
4                 30          0         2    1                          2  
..               ...        ...       ...  ...                        ...  
695               22          1         2    0                          8  
696               24          0         1    2                          3  
697               25          1         0    0                          8  
698               25          1         0    0                          2  
699               25          0         1    1                          2  

[700 rows x 15 columns]

In [ ]:
df.drop(columns = 'Absenteeism Time in Hours',inplace = True)

In [221]:
df

Reason_1  Reason_2  Reason_3  Reason_4  Month Value  Day of the Week  \
0           0         0         0         1            7                1   
1           0         0         0         0            7                1   
2           0         0         0         1            7                2   
3           1         0         0         0            7                3   
4           0         0         0         1            7                3   
..        ...       ...       ...       ...          ...              ...   
695         1         0         0         0            5                2   
696         1         0         0         0            5                2   
697         1         0         0         0            5                3   
698         0         0         0         1            5                3   
699         0         0         0         1            5                3   

     Transportation Expense  Distance to Work  Age  Daily Work Load Average  \
0                       289                36   33                  239.554   
1                       118                13   50                  239.554   
2                       179                51   38                  239.554   
3                       279                 5   39                  239.554   
4                       289                36   33                  239.554   
..                      ...               ...  ...                      ...   
695                     179                22   40                  237.656   
696                     225                26   28                  237.656   
697                     330                16   28                  237.656   
698                     235                16   32                  237.656   
699                     291                31   40                  237.656   

     Body Mass Index  Education  Children  Pet  
0                 30          0         2    1  
1                 31          0         1    0  
2                 31          0         0    0  
3                 24          0         2    0  
4                 30          0         2    1  
..               ...        ...       ...  ...  
695               22          1         2    0  
696               24          0         1    2  
697               25          1         0    0  
698               25          1         0    0  
699               25          0         1    1  

[700 rows x 14 columns]

In [226]:
targets.sum()/targets.shape[0]

xcols =df.iloc[:,:-1] #all columns but last 
y=targets
cols = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Month Value',
       'Day of the Week', 'Transportation Expense', 'Distance to Work', 'Age',
       'Daily Work Load Average', 'Body Mass Index', 'Education', 'Children',
       'Pet']
icols = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4', 'Day of the Week', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Education', 'Children',
       'Pet']
allcols=cols+['Absenteeism Time in Hours']
x1 = df[cols]

['Reason_1',
 'Reason_2',
 'Reason_3',
 'Reason_4',
 'Month Value',
 'Day of the Week',
 'Transportation Expense',
 'Distance to Work',
 'Age',
 'Daily Work Load Average',
 'Body Mass Index',
 'Education',
 'Children',
 'Pet',
 'Absenteeism Time in Hours']

In [227]:
cols2scale = ['Day of the Week', 'Transportation Expense', 'Age',
       'Body Mass Index', 'Children',
       'Pet']
nonscale = ['Reason_1', 'Reason_2', 'Reason_3', 'Reason_4','Education']
x1 = df[cols2scale]

In [228]:
scaler = StandardScaler()
scaled_x1 = scaler.fit_transform(x1)
scaled_x1 = pd.DataFrame(scaled_x1, columns=cols2scale)

In [229]:
ns =df[nonscale]

In [230]:
x = pd.concat([scaled_x1,ns],axis=1)
x

Day of the Week  Transportation Expense       Age  Body Mass Index  \
0          -0.800950                1.005844 -0.536062         0.767431   
1          -0.800950               -1.574681  2.130803         1.002633   
2          -0.232900               -0.654143  0.248310         1.002633   
3           0.335149                0.854936  0.405184        -0.643782   
4           0.335149                1.005844 -0.536062         0.767431   
..               ...                     ...       ...              ...   
695        -0.232900               -0.654143  0.562059        -1.114186   
696        -0.232900                0.040034 -1.320435        -0.643782   
697         0.335149                1.624567 -1.320435        -0.408580   
698         0.335149                0.190942 -0.692937        -0.408580   
699         0.335149                1.036026  0.562059        -0.408580   

     Children       Pet  Reason_1  Reason_2  Reason_3  Reason_4  Education  
0    0.880469  0.268487         0         0         0         1          0  
1   -0.019280 -0.589690         0         0         0         0          0  
2   -0.919030 -0.589690         0         0         0         1          0  
3    0.880469 -0.589690         1         0         0         0          0  
4    0.880469  0.268487         0         0         0         1          0  
..        ...       ...       ...       ...       ...       ...        ...  
695  0.880469 -0.589690         1         0         0         0          1  
696 -0.019280  1.126663         1         0         0         0          0  
697 -0.919030 -0.589690         1         0         0         0          1  
698 -0.919030 -0.589690         0         0         0         1          1  
699 -0.019280  0.268487         0         0         0         1          0  

[700 rows x 11 columns]

In [231]:
x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.8)

In [232]:
clf = LogisticRegression().fit(x_train,y_train)
clf.score(x_train,y_train)


0.7875

In [235]:
clf.intercept_

array([-1.72694246])

In [236]:
clf.coef_

array([[-0.12561764,  0.67707737, -0.24006754,  0.23465522,  0.4435995 ,
        -0.35698007,  2.8833311 ,  0.55576248,  2.90848609,  0.94311928,
         0.1904145 ]])

In [237]:
allcols = x.columns.values

In [238]:
sumdf = pd.DataFrame(columns=['Features'],data = allcols)
sumdf['Coef'] = np.transpose(clf.coef_)
sumdf.index = sumdf.index +1
sumdf.loc[0] = ['Intercept', clf.intercept_[0]]
sumdf.sort_index(inplace=True)
sumdf

Features      Coef
0                Intercept -1.726942
1          Day of the Week -0.125618
2   Transportation Expense  0.677077
3                      Age -0.240068
4          Body Mass Index  0.234655
5                 Children  0.443599
6                      Pet -0.356980
7                 Reason_1  2.883331
8                 Reason_2  0.555762
9                 Reason_3  2.908486
10                Reason_4  0.943119
11               Education  0.190414

In [239]:
sumdf['odds']= np.exp(sumdf['Coef'])

In [240]:
sumdf.sort_values('Coef',axis=0,ascending=False,inplace=True)

In [241]:
sumdf

Features      Coef       odds
9                 Reason_3  2.908486  18.329029
7                 Reason_1  2.883331  17.873713
10                Reason_4  0.943119   2.567979
2   Transportation Expense  0.677077   1.968117
8                 Reason_2  0.555762   1.743270
5                 Children  0.443599   1.558306
4          Body Mass Index  0.234655   1.264473
11               Education  0.190414   1.209751
1          Day of the Week -0.125618   0.881952
3                      Age -0.240068   0.786575
6                      Pet -0.356980   0.699786
0                Intercept -1.726942   0.177827

In [243]:
clf.score(x_test,y_test)

0.7214285714285714

In [245]:
proba = clf.predict_proba(x_test)

In [247]:
proba[:,1]

array([0.80363912, 0.22324268, 0.11491101, 0.5833542 , 0.21579514,
       0.24694042, 0.27442565, 0.2542126 , 0.34082005, 0.7213245 ,
       0.6942171 , 0.94153922, 0.62947656, 0.22324268, 0.72140508,
       0.67008791, 0.24092285, 0.42413666, 0.37573647, 0.76678885,
       0.42711947, 0.17796541, 0.19914479, 0.21111366, 0.70870382,
       0.92700316, 0.68838614, 0.13024252, 0.66873375, 0.72743789,
       0.33098297, 0.28886021, 0.68299955, 0.75224892, 0.67287739,
       0.71306259, 0.40412621, 0.52819495, 0.19262315, 0.22324268,
       0.18832365, 0.51034745, 0.45787119, 0.25203576, 0.75876805,
       0.51560294, 0.2463164 , 0.6569814 , 0.1994744 , 0.67287739,
       0.42179977, 0.2039645 , 0.72987941, 0.73551746, 0.93510149,
       0.12237029, 0.35634974, 0.78254677, 0.86283516, 0.38971063,
       0.81633076, 0.26550334, 0.2039645 , 0.76678885, 0.37028002,
       0.63002218, 0.91350855, 0.64596029, 0.61987558, 0.9073137 ,
       0.67008791, 0.42142055, 0.24315424, 0.2542126 , 0.77494

In [248]:
import pickle

In [250]:
with open('model','wb') as file:
    pickle.dump(clf,file)

In [251]:
with open('scaler','wb') as file:
    pickle.dump(scaler, file)