In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()
import tensorflow as tf
from tensorflow.keras.layers import Input, Dense, SimpleRNN, Flatten
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import SGD, Adam

In [2]:
N = 1
T = 10
D = 3
K = 2
X = np.random.rand(N,T,D)

In [4]:
M = 5 # number of hidden units
i = Input(shape=(T,D))
x = SimpleRNN(M)(i)
x = Dense(K)(x)

model = Model(i,x)

In [6]:
# Get output
Yhat = model.predict(X)
Yhat

array([[-1.6171232,  0.5460532]], dtype=float32)

In [7]:
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 10, 3)]           0         
_________________________________________________________________
simple_rnn (SimpleRNN)       (None, 5)                 45        
_________________________________________________________________
dense (Dense)                (None, 2)                 12        
Total params: 57
Trainable params: 57
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.layers[1].get_weights()

[array([[ 0.6005083 ,  0.45847172,  0.6281082 , -0.17877835, -0.4624193 ],
        [ 0.35695213, -0.29962927,  0.385979  , -0.65406567, -0.02603072],
        [ 0.12901855, -0.11356992,  0.28947717, -0.5322682 ,  0.1664744 ]],
       dtype=float32),
 array([[ 7.6740456e-01, -4.2393076e-01, -3.5534546e-02, -4.5813087e-01,
         -1.4221908e-01],
        [-1.8088230e-01, -1.1269168e-01,  4.1929910e-01,  4.2399541e-02,
         -8.8146055e-01],
        [ 3.8902679e-01,  4.9105853e-01,  7.4552929e-01,  7.2520092e-02,
          2.1551517e-01],
        [ 4.7647658e-01,  2.3901719e-01, -3.9227021e-01,  6.9477773e-01,
         -2.8151196e-01],
        [ 3.0127610e-05,  7.1366346e-01, -3.3650574e-01, -5.4803586e-01,
         -2.7767810e-01]], dtype=float32),
 array([0., 0., 0., 0., 0.], dtype=float32)]

In [9]:
a ,b ,c = model.layers[1].get_weights()
print(a.shape,b.shape,c.shape)

(3, 5) (5, 5) (5,)


In [10]:
Wx , Wh, bh = model.layers[1].get_weights()
Wo , bo = model.layers[2].get_weights()

In [13]:
h_last = np.zeros(M) # Initial hidden state
x = X[0]
Yhats = []
for t in range(T):
    h = np.tanh(x[t].dot(Wx) + h_last.dot(Wh) + bh)
    y = h.dot(Wo) + bo #Only need this value for last iter
    Yhats.append(y)
    
    #assign h t h_last
    h_last = h
print(Yhats[-1])

[-1.61712326  0.54605308]
